In [8]:
#Importing boston data
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import load_boston
boston = load_boston()
bos = pd.DataFrame(boston.data)

#Creating dependent and independent variables
X = bos.iloc[:,:-1].values
y = boston.target

#Splitting dataset into training and test dataset
from sklearn.cross_validation import train_test_split
X_Train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

#Applying simple linear regression
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_Train,y_train)

#predicting y_test

y_pred = lm.predict(X_test)
print(lm.intercept_)
print(lm.coef_)

25.015023879559905
[-1.82681953e-01  3.77790430e-02 -4.53984847e-02  2.94816275e+00
 -1.88243660e+01  5.91502977e+00 -5.63113844e-02 -1.57378046e+00
  2.41347849e-01 -9.92509408e-03 -1.14671355e+00  1.12631124e-02]


In [9]:
y_pred

array([26.02530738, 20.06795225, 28.25459487, 10.65992197, 22.30852578,
       16.94355565, 19.69796079, 19.79718961, 17.96135059, 17.82700213,
        0.94991127, 18.14301468, 17.53288114,  6.62542877, 37.49667506,
       33.65067334, 21.4930886 , 37.27489104, 30.78177783, 22.30195191,
       23.6412372 , 22.12792476, 20.71303191, 30.55640796, 22.27130694,
        2.18496351, 16.5665292 , 16.30576493, 36.0057936 , 22.09461677,
       18.78424971, 16.95790543, 17.86887357, 24.14273409, 27.95234256,
       18.18593389, 14.34322893, 20.92091119, 18.07675104, 18.95254074,
       26.90689827, 22.91153109, 22.95477006, 14.62279302, 22.84579205,
       23.72040394, 21.38668668, 22.48005112, 13.41884332, 23.60547949,
       20.36489163, 21.02237376, 24.10518713, 32.7437065 , 12.19350867,
       24.39605697, 21.79327403, 15.59305009,  5.85941927, 23.52751297,
       16.68178547, 22.09903605, 33.8725599 , 30.61868788, 17.53137124,
       32.40144896, 19.92601091, 22.75757946, 20.94859209, 24.04

In [3]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [5]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
boston

{'DESCR': "Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per